import type { NextPage } from 'next'
import Head from 'next/head'
import About from '../components/About'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Marquee from '../components/Marquee'
import Quotes from '../components/Quotes'
import Shop from '../components/Shop'
import SubMenu from '../components/SubMenu'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Deplace Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <SubMenu />

      <main>
        <Hero />
        <Marquee />
        <About />
        <Shop />
        <Quotes />
      </main>

      <Footer />
    </div>
  )
}

export default Home
